// Generated for: node-api-dotnet-simple 1.0.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.5.0.0
/* eslint-disable */


declare module 'node-api-dotnet' {

	export namespace Simple {
		export class Greeter {
			constructor();

			Greet(name: string): void;
		}
	}
}

declare module 'node-api-dotnet-simple' {
	export * from 'node-api-dotnet';
}

export * from 'node-api-dotnet';
